apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscriptions.ibmsls.name }}
  annotations:
spec:
  {{- toYaml .Values.subscriptions.ibmsls.subscription | nindent 2 }}